services:
  app:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/${ENVIRONMENT}/app/Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    environment:
      - INTERNAL_API_URL
      - NEXT_PUBLIC_API_URL
      - AUTH_GOOGLE_ID
      - AUTH_GOOGLE_SECRET
      - AUTH_GITHUB_ID
      - AUTH_GITHUB_SECRET
      - AUTH_SECRET
      - AUTH_URL
    extends:
      file: ./docker/app.yml
      service: ${ENVIRONMENT}
    networks:
      - stack
    ports:
      - ${FRONTEND_PORT}:3000
    restart: unless-stopped
    volumes:
      - data_app:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    healthcheck:
      test: curl --fail -s ${INTERNAL_API_URL}/api/status || exit 1
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 4
  
volumes:
  data_app:
    name: ${DATA_APP}
    external: true
  node_modules:
  build:

networks:
  stack:
    external: true
    name: app_network