import { auth } from "@/lib/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/layout/providers";
import Layout from "@/components/layout";
import { AuthProvider } from "@/context/auth-context";
import { NuqsAdapter } from 'nuqs/adapters/next/app';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" 
      className={`${inter.className}`}  
    >
      <body className="bg-white text-gray-900">
        <NuqsAdapter>
          <Providers session={session}>
            <AuthProvider>
              <Layout>
                  <main className="min-h-[500px]">{children}</main>
              </Layout>
            </AuthProvider>
          </Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
